title: Learn CS:APP
description: "Computer Systems: A Programmer's Perspective 學習筆記"
author:
  name: "Wei-Hsiang Teng"
  email: "f96222069@gmail.com"
  url: "https://ashishchaudhary.in/hacker-blog"

baseurl: /

source: .
destination: ./_site
permalink: /:title
paginate: 3
paginate_path: /page/:num/

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

future: true
plugins:
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-sitemap

# Custom variables
owner : "Wei-Hsiang"
year : "2020"
